/*
-- Query: SELECT * FROM numeracy.m03_level
LIMIT 0, 1000

-- Date: 2015-08-08 18:13
*/
INSERT INTO `m03_level` (`M03LEVELID`,`LABEL`,`M11STATUSID`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (1,'Beginner',6,NULL,NULL,NULL,NULL);
INSERT INTO `m03_level` (`M03LEVELID`,`LABEL`,`M11STATUSID`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (2,'Intermediate',6,NULL,NULL,NULL,NULL);
INSERT INTO `m03_level` (`M03LEVELID`,`LABEL`,`M11STATUSID`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (3,'Advanced',6,NULL,NULL,NULL,NULL);
