
/*
-- Query: SELECT * FROM numeracy.m10_file_type
-- Date: 2015-08-03 12:05
*/
INSERT INTO `m10_file_type` (`M10TYPEID`,`LABLE`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (1,'IMAGE',NOW(),'ADMIN',NULL,NULL);
INSERT INTO `m10_file_type` (`M10TYPEID`,`LABLE`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (2,'AUDIO',NOW(),'ADMIN',NULL,NULL);
INSERT INTO `m10_file_type` (`M10TYPEID`,`LABLE`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (3,'VIDEO',NOW(),'ADMIN',NULL,NULL);
INSERT INTO `m10_file_type` (`M10TYPEID`,`LABLE`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (4,'PDF',NOW(),'ADMIN',NULL,NULL);
INSERT INTO `m10_file_type` (`M10TYPEID`,`LABLE`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (5,'TEXT',NOW(),'ADMIN',NULL,NULL);
INSERT INTO `m10_file_type` (`M10TYPEID`,`LABLE`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (6,'HTML',NOW(),'ADMIN',NULL,NULL);



INSERT INTO `M11_STATUS` (`M11STATUSID`,`CODE`,`LABEL`,`CREATEDON`,`MODIFIEDON`,`CREATEBY`) VALUES (1,'REG0001','UNREGISTERED',NOW(),NULL,'ADMIN');
INSERT INTO `M11_STATUS` (`M11STATUSID`,`CODE`,`LABEL`,`CREATEDON`,`MODIFIEDON`,`CREATEBY`) VALUES (2,'REG0002','REGISTERED',NOW(),NULL,'ADMIN');
INSERT INTO `M11_STATUS` (`M11STATUSID`,`CODE`,`LABEL`,`CREATEDON`,`MODIFIEDON`,`CREATEBY`) VALUES (3,'REG0003','REGISTRATION PENDING',NOW(),NULL,'ADMIN');
INSERT INTO `M11_STATUS` (`M11STATUSID`,`CODE`,`LABEL`,`CREATEDON`,`MODIFIEDON`,`CREATEBY`) VALUES (4,'REG0004','UNVERIFIED',NOW(),NULL,'ADMIN');
INSERT INTO `M11_STATUS` (`M11STATUSID`,`CODE`,`LABEL`,`CREATEDON`,`MODIFIEDON`,`CREATEBY`) VALUES (5,'REG0005','VERIFIED',NOW(),NULL,'ADMIN');
INSERT INTO `M11_STATUS` (`M11STATUSID`,`CODE`,`LABEL`,`CREATEDON`,`MODIFIEDON`,`CREATEBY`) VALUES (6,'STA0001','ACTIVE',NOW(),NULL,'ADMIN');
INSERT INTO `M11_STATUS` (`M11STATUSID`,`CODE`,`LABEL`,`CREATEDON`,`MODIFIEDON`,`CREATEBY`) VALUES (7,'STA0002','INACTIVE',NOW(),NULL,'ADMIN');


/*
-- Query: SELECT * FROM numeracy.m14_login
-- Date: 2015-08-03 11:34
*/
INSERT INTO `m14_login` (`M14LOGINID`,`username`,`password`) VALUES (1,'admin@numeracy.com','Zaq12wsx');


/*
-- Query: SELECT * FROM numeracy.m02_category
-- Date: 2015-08-03 12:33
*/
INSERT INTO `m02_category` (`M02CATEGORYID`,`LABEL`,`M11STATUSID`,`STARTAGE`,`ENDAGE`,`GENDER`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (1,'CHILD-1',6,3,6,'A','2015-08-03 12:32:50','ADMIN',NULL,NULL);
INSERT INTO `m02_category` (`M02CATEGORYID`,`LABEL`,`M11STATUSID`,`STARTAGE`,`ENDAGE`,`GENDER`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (2,'CHILD-2',6,7,10,'A','2015-08-03 12:32:50','ADMIN',NULL,NULL);
INSERT INTO `m02_category` (`M02CATEGORYID`,`LABEL`,`M11STATUSID`,`STARTAGE`,`ENDAGE`,`GENDER`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (3,'CHILD-3',6,11,13,'A','2015-08-03 12:32:50','ADMIN',NULL,NULL);
INSERT INTO `m02_category` (`M02CATEGORYID`,`LABEL`,`M11STATUSID`,`STARTAGE`,`ENDAGE`,`GENDER`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (4,'TEEN',6,14,18,'A','2015-08-03 12:32:50','ADMIN',NULL,NULL);
INSERT INTO `m02_category` (`M02CATEGORYID`,`LABEL`,`M11STATUSID`,`STARTAGE`,`ENDAGE`,`GENDER`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (5,'ADULT',6,19,29,'A','2015-08-03 12:32:50','ADMIN',NULL,NULL);


/*
-- Query: SELECT * FROM numeracy.m03_level
LIMIT 0, 1000

-- Date: 2015-08-08 18:13
*/
INSERT INTO `m03_level` (`M03LEVELID`,`LABEL`,`M11STATUSID`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (1,'Beginner',6,NULL,NULL,NULL,NULL);
INSERT INTO `m03_level` (`M03LEVELID`,`LABEL`,`M11STATUSID`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (2,'Intermediate',6,NULL,NULL,NULL,NULL);
INSERT INTO `m03_level` (`M03LEVELID`,`LABEL`,`M11STATUSID`,`CREATEDON`,`CREATEDBY`,`MODIFIEDON`,`MODIFIEDBY`) VALUES (3,'Advanced',6,NULL,NULL,NULL,NULL);

